import image1 from "@/app/images/heroImages/heroImage1.jpg";
import image2 from "@/app/images/heroImages/heroImage2.jpg";
import image3 from "@/app/images/heroImages/heroImage3.jpg";
import image4 from "@/app/images/heroImages/heroImage4.jpg";
import image5 from "@/app/images/heroImages/heroImage5.jpg";
import fourbedroomduplexcarcass from "@/app/images/propertyImages/4bedroomcarcass/image5.jpeg";
import fivebedroomduplexcarcass from "@/app/images/propertyImages/5bedroomcarcass/image9.jpeg";
import onebedroomcarcass from "@/app/images/propertyImages/1bedroomcarcass/image4.jpeg";
import oligarchstandard from "@/app/images/propertyImages/oligarchstandard5and6bedroom/image3.jpeg";
import twobedroomapartmentcarcass from "@/app/images/propertyImages/2bedroomapartmentcarcass/image7.jpeg";
import threebedroomsemidetachedduplex from "@/app/images/propertyImages/3bedroomsemidetachedduplex/image2.jpeg";
import threebedroomterracedduplex from "@/app/images/propertyImages/3bedroomterraceduplex/image8.jpeg";
import fivebedroompenthouse from "@/app/images/propertyImages/5bedroompenthouse/image1.jpeg";
import fivebedroomterraceduplex from "@/app/images/propertyImages/5bedroomterraceduplex/image1.jpeg";
import twobedroomapartmentgymelevator from "@/app/images/propertyImages/2bedroomapartmentwithgymandelevator/image7.jpeg";
import fourbedroomcontemporaryduplex from "@/app/images/propertyImages/4bedroomcontemporaryduplex/image1.jpeg";
import fourbedroomduplexalongvoiceofnigeria from "@/app/images/propertyImages/4bedroomduplexalongvoiceofnigeria/image5.jpeg";
import fourbedroomterracedduplex from "@/app/images/propertyImages/4bedroomterraceduplex/image10.jpeg";
import { propertyImagesModel } from "./propertyImagesModel";

const newArrivals = [
  {
    uuid: "123e4567-e89b-12d3-a456-426614174001",
    image: fivebedroomduplexcarcass,
    title: "5 bedroom duplex carcass",
    description:
      "5 Bedroom fully detached duplex carcass located in an estate behind FIRS office opposite dunamis church airport road lugbe Abuja.",
    price: "60,000,000",
    category: "house",
    type: "sale",
    number_of_bedrooms: 5,
    number_of_bathrooms: 5,
    number_of_toilets: 6,
    location: "Airport road Lugbe, Abuja",
    state: "abuja",
    image_count: 9,
    video: true,
    videoLink: "https://www.youtube.com/watch?v=hostbXQIWcU",
    imagesArray: propertyImagesModel.fiveBedroomImages,
  },
  {
    uuid: "123e4567-e89b-12d3-a456-426614174002",
    image: fourbedroomduplexcarcass,
    title: "4 Bedroom Semi-detached duplex",
    description: "Newly built 4 Bedroom Semi-detached duplex",
    price: "150,000,000",
    category: "house",
    type: "sale",
    number_of_bedrooms: 4,
    number_of_toilets: 5,
    number_of_bathrooms: 4,
    location: "Apo, Abuja",
    state: "FCT",
    image_count: 10,
    video: true,
    videoLink: "https://www.youtube.com/watch?v=w0cAmpTNx3s&t=22s",
    imagesArray: propertyImagesModel.fourBedroomImages,
  },
  {
    uuid: "123e4567-e89b-12d3-a456-426614174003",
    image: onebedroomcarcass,
    title: "1 Bedroom advance carcass",
    description:
      "One bedroom advance carcass in a serene and secured estate at lifecamp abuja",
    price: "13,500,000",
    category: "house",
    type: "rent",
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    number_of_toilets: 1,
    location: "LifeCamp, Abuja",
    state: "FCT",
    image_count: 6,
    videoLink: "",
    imagesArray: propertyImagesModel.oneBedroomCarcassImages,
  },
  {
    uuid: "123e4567-e89b-12d3-a456-426614174004",
    image: oligarchstandard,
    title: "Oligarch Standard 6 Bedroom Super Luxury Mansion ",
    description:
      "Oligarch Standard 5 and 6 Bedroom Super Luxury Mansion with Cinema, Pool and Rooftop Terrace",
    price: "650,000,000",
    category: "house",
    type: "sale",
    number_of_bedrooms: 6,
    number_of_bathrooms: 6,
    number_of_toilets: 7,
    location: "Osapa Lekki, Lagos",
    state: "Lagos",
    image_count: 10,
    videoLink: "",
    imagesArray: propertyImagesModel.oligarchStandard,
    keyFeatures: [
      "Greatly Finished To Detail",
      "Zenith Quality Appurtenances",
      "Swimming Pool",
      "Home Cinema",
      "Unconventional Stunning Architecture",
      "Bespoke Woodwork",
      "Unparalleled Beautiful Aesthetics",
      "Inbuilt Audio System",
      "Green Area",
      "Fully Furnished Kitchen",
      "Family Lounge",
      "Luxury Sanitary Wares",
      "Decent Sit Out Area",
      "Rooftop Terrace",
      "Boy's Quarters",
      "Ample Parking Space",
      "Glorious Neighborhood",
    ],
  },
];

export const propertyData = {
  newArrivals: [
    {
      uuid: "123e4567-e89b-12d3-a456-426614174001",
      image: fivebedroomduplexcarcass,
      title: "5 bedroom duplex carcass",
      description:
        "5 Bedroom fully detached duplex carcass located in an estate behind FIRS office opposite dunamis church airport road lugbe Abuja.",
      price: "60,000,000",
      category: "house",
      type: "sale",
      number_of_bedrooms: 5,
      number_of_bathrooms: 5,
      number_of_toilets: 6,
      location: "Airport road Lugbe, Abuja",
      state: "abuja",
      image_count: 9,
      video: true,
      videoLink: "https://www.youtube.com/watch?v=hostbXQIWcU",
      imagesArray: propertyImagesModel.fiveBedroomImages,
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174002",
      image: fourbedroomduplexcarcass,
      title: "4 Bedroom Semi-detached duplex",
      description: "Newly built 4 Bedroom Semi-detached duplex",
      price: "150,000,000",
      category: "house",
      type: "sale",
      number_of_bedrooms: 4,
      number_of_toilets: 5,
      number_of_bathrooms: 4,
      location: "Apo, Abuja",
      state: "FCT",
      image_count: 10,
      video: true,
      videoLink: "https://www.youtube.com/watch?v=w0cAmpTNx3s&t=22s",
      imagesArray: propertyImagesModel.fourBedroomImages,
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174003",
      image: onebedroomcarcass,
      title: "1 Bedroom advance carcass",
      description:
        "One bedroom advance carcass in a serene and secured estate at lifecamp abuja",
      price: "13,500,000",
      category: "house",
      type: "sale",
      number_of_bedrooms: 1,
      number_of_bathrooms: 1,
      number_of_toilets: 1,
      location: "LifeCamp, Abuja",
      state: "FCT",
      image_count: 6,
      videoLink: "",
      imagesArray: propertyImagesModel.oneBedroomCarcassImages,
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174004",
      image: oligarchstandard,
      title: "Oligarch Standard 6 Bedroom Super Luxury Mansion ",
      description:
        "Oligarch Standard 5 and 6 Bedroom Super Luxury Mansion with Cinema, Pool and Rooftop Terrace",
      price: "650,000,000",
      category: "house",
      type: "sale",
      number_of_bedrooms: 6,
      number_of_bathrooms: 6,
      number_of_toilets: 7,
      location: "Osapa Lekki, Lagos",
      state: "Lagos",
      image_count: 10,
      videoLink: "",
      imagesArray: propertyImagesModel.oligarchStandard,
      keyFeatures: [
        "Greatly Finished To Detail",
        "Zenith Quality Appurtenances",
        "Swimming Pool",
        "Home Cinema",
        "Unconventional Stunning Architecture",
        "Bespoke Woodwork",
        "Unparalleled Beautiful Aesthetics",
        "Inbuilt Audio System",
        "Green Area",
        "Fully Furnished Kitchen",
        "Family Lounge",
        "Luxury Sanitary Wares",
        "Decent Sit Out Area",
        "Rooftop Terrace",
        "Boy's Quarters",
        "Ample Parking Space",
        "Glorious Neighborhood",
      ],
    },
  ],
  allProperties: [
    ...newArrivals,
    {
      uuid: "123e4567-e89b-12d3-a456-426614174005",
      image: twobedroomapartmentcarcass,
      title: "2 Bedroom Apartment Carcass",
      description: "2 Bedroom Apartment Carcass at LifeCamp Abuja",
      price: "27,000,000",
      category: "house",
      type: "sale",
      number_of_bedrooms: 2,
      number_of_bathrooms: 2,
      number_of_toilets: 3,
      location: "LifeCamp, Abuja",
      state: "FCT",
      country: "Nigeria",
      image_count: 8,
      video: true,
      imagesArray: propertyImagesModel.twobedroomapartmentcarcassImages,
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174006",
      image: twobedroomapartmentgymelevator,
      title: "2 Bedroom Apartment with Gym and Elevator",
      description: "Beautifully finished 2 Bedroom Apartment with Gym and Elevator",
      price: "270,000,000",
      category: "house",
      type: "sale",
      number_of_bedrooms: 2,
      number_of_bathrooms: 2,
      number_of_toilets: 3,
      location: "Lekki Phase 1, Lagos",
      state: "Lagos",
      country: "Nigeria",
      image_count: 8,
      video: true,
      imagesArray: propertyImagesModel.twobedroomapartmentcarcassImages,
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174007",
      image: image3,
      title: "Downtown Office Space",
      description: "Modern office space in a high-traffic commercial area.",
      price: "15,000,000",
      date_uploaded: "2024-10-07",
      category: "commercial-property",
      type: "rent",
      number_of_bedrooms: null,
      number_of_bathrooms: 2,
      location: "Wuse, Abuja",
      state: "abuja",
      country: "Nigeria",
      image_count: 2,
      video: true,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: true,
        gym: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174008",
      image: image4,
      title: "Luxury Apartment",
      description:
        "A luxurious apartment with stunning views and modern amenities.",
      price: "80,000,000",
      date_uploaded: "2024-10-06",
      category: "house",
      type: "sale",
      number_of_bedrooms: 3,
      number_of_bathrooms: 2,
      location: "Victoria Island, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 5,
      video: true,
      key_features: {
        mosque: false,
        church: true,
        security: true,
        hospital: false,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174009",
      image: image5,
      title: "Exclusive Beachfront Land",
      description: "Premium land for sale with direct access to the beach.",
      price: "200,000,000",
      date_uploaded: "2024-09-25",
      category: "land",
      type: "sale",
      number_of_bedrooms: null,
      number_of_bathrooms: null,
      location: "Lekki Phase 1, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 3,
      video: false,
      key_features: {
        security: true,
        hospital: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174010",
      image: image1,
      title: "Classic Shortlet Apartment",
      description:
        "Fully furnished shortlet apartment ideal for business travelers.",
      price: "30,000",
      duration: "per-night",
      date_uploaded: "2024-09-10",
      category: "house",
      type: "shortlet",
      number_of_bedrooms: 2,
      number_of_bathrooms: 1,
      location: "Ikoyi, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 5,
      video: true,
      key_features: {
        mosque: false,
        church: true,
        security: true,
        hospital: true,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174012",
      image: image3,
      title: "Luxury Penthouse",
      description:
        "A luxurious penthouse with panoramic city views and top-notch amenities.",
      price: "250,000,000",
      date_uploaded: "2024-08-20",
      category: "house",
      type: "sale",
      number_of_bedrooms: 4,
      number_of_bathrooms: 4,
      location: "Asokoro, Abuja",
      state: "abuja",
      country: "Nigeria",
      image_count: 8,
      video: true,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: true,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174013",
      image: image4,
      title: "Prime Commercial Property",
      description:
        "High-visibility commercial property ideal for businesses and retail.",
      price: "45,000,000",
      date_uploaded: "2024-08-15",
      category: "commercial-property",
      type: "rent",
      number_of_bedrooms: null,
      number_of_bathrooms: 2,
      location: "Onitsha, Anambra State",
      state: "anambra",
      country: "Nigeria",
      image_count: 2,
      video: true,
      key_features: {
        mosque: true,
        church: false,
        security: true,
        hospital: true,
        gym: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174014",
      image: image5,
      title: "City Center Land",
      description:
        "Land in the heart of the city with excellent road networks.",
      price: "90,000,000",
      date_uploaded: "2024-08-05",
      category: "land",
      type: "sale",
      number_of_bedrooms: null,
      number_of_bathrooms: null,
      location: "Benin City, Edo State",
      state: "edo",
      country: "Nigeria",
      image_count: 1,
      video: false,
      key_features: {
        security: true,
        hospital: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174015",
      image: image1,
      title: "Serene Duplex",
      description:
        "A serene and spacious duplex in a family-friendly neighborhood.",
      price: "50,000,000",
      date_uploaded: "2024-07-30",
      category: "house",
      type: "sale",
      number_of_bedrooms: 3,
      number_of_bathrooms: 3,
      location: "Abeokuta, Ogun State",
      state: "ogun",
      country: "Nigeria",
      image_count: 4,
      video: false,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: false,
        gym: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174016",
      image: image2,
      title: "Affordable Family Home",
      description: "A cozy family home in a serene environment.",
      price: "25,000,000",
      date_uploaded: "2024-07-28",
      category: "house",
      type: "sale",
      number_of_bedrooms: 3,
      number_of_bathrooms: 2,
      location: "Mowe, Ogun State",
      state: "ogun",
      country: "Nigeria",
      image_count: 3,
      video: false,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: true,
        gym: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174017",
      image: image3,
      title: "Commercial Warehouse",
      description: "Large warehouse with good access roads for logistics.",
      price: "70,000,000",
      date_uploaded: "2024-07-27",
      category: "commercial-property",
      type: "rent",
      number_of_bedrooms: null,
      number_of_bathrooms: 1,
      location: "Apapa, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 4,
      video: true,
      key_features: {
        security: true,
        hospital: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174018",
      image: image4,
      title: "Luxury Mansion",
      description:
        "A sprawling mansion with luxurious finishes and ample space.",
      price: "500,000,000",
      date_uploaded: "2024-07-25",
      category: "house",
      type: "sale",
      number_of_bedrooms: 6,
      number_of_bathrooms: 5,
      location: "Banana Island, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 10,
      video: true,
      key_features: {
        mosque: false,
        church: false,
        security: true,
        hospital: true,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174019",
      image: image5,
      title: "Budget Commercial Shop",
      description: "A small but strategically located shop in a busy area.",
      price: "1,500,000",
      date_uploaded: "2024-07-22",
      category: "commercial-property",
      type: "rent",
      number_of_bedrooms: null,
      number_of_bathrooms: 1,
      location: "Mushin, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 2,
      video: false,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: false,
        gym: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174020",
      image: image1,
      title: "Executive Duplex",
      description:
        "Spacious duplex ideal for large families or corporate rentals.",
      price: "100,000,000",
      date_uploaded: "2024-07-20",
      category: "house",
      type: "sale",
      number_of_bedrooms: 5,
      number_of_bathrooms: 4,
      location: "Lekki, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 6,
      video: true,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: true,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174021",
      image: image2,
      title: "Downtown Plot",
      description: "Perfect plot for residential or commercial development.",
      price: "40,000,000",
      date_uploaded: "2024-07-18",
      category: "land",
      type: "sale",
      number_of_bedrooms: null,
      number_of_bathrooms: null,
      location: "Port Harcourt, Rivers State",
      state: "rivers",
      country: "Nigeria",
      image_count: 1,
      video: false,
      key_features: {
        security: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174022",
      image: image3,
      title: "Urban Office Block",
      description: "Modern office space with all essential amenities.",
      price: "12,000,000",
      date_uploaded: "2024-07-15",
      category: "commercial-property",
      type: "rent",
      number_of_bedrooms: null,
      number_of_bathrooms: 4,
      location: "Ikeja, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 3,
      video: true,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: true,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174023",
      image: image4,
      title: "Residential Plot with Title",
      description:
        "Land plot with proper documentation and excellent location.",
      price: "25,000,000",
      date_uploaded: "2024-07-12",
      category: "land",
      type: "sale",
      number_of_bedrooms: null,
      number_of_bathrooms: null,
      location: "Abeokuta, Ogun State",
      state: "ogun",
      country: "Nigeria",
      image_count: 2,
      video: false,
      key_features: {
        security: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174024",
      image: image5,
      title: "Warehouse for Rent",
      description: "Spacious warehouse available for lease.",
      price: "25,000,000",
      date_uploaded: "2024-07-10",
      category: "commercial-property",
      type: "sale",
      number_of_bedrooms: null,
      number_of_bathrooms: 2,
      location: "Kano, Kano State",
      state: "kano",
      country: "Nigeria",
      image_count: 3,
      video: false,
      key_features: {
        security: true,
        hospital: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174025",
      image: image1,
      title: "Farm Land for Sale",
      description: "Sprawling land suitable for agricultural purposes.",
      price: "10,000,000",
      date_uploaded: "2024-07-08",
      category: "land",
      type: "sale",
      number_of_bedrooms: null,
      number_of_bathrooms: null,
      location: "Makurdi, Benue State",
      state: "benue",
      country: "Nigeria",
      image_count: 1,
      video: false,
      key_features: {
        security: false,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174026",
      image: image2,
      title: "Seaside Apartment",
      description: "Fully furnished apartment with stunning sea views.",
      price: "50,000",
      duration: "per night",
      date_uploaded: "2024-07-05",
      category: "house",
      type: "shortlet",
      number_of_bedrooms: 2,
      number_of_bathrooms: 1,
      location: "Victoria Island, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 5,
      video: true,
      key_features: {
        mosque: false,
        church: true,
        security: true,
        hospital: true,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
    {
      uuid: "123e4567-e89b-12d3-a456-426614174027",
      image: image3,
      title: "Urban Office Block",
      description: "Modern office space with all essential amenities.",
      price: "12,000,000",
      date_uploaded: "2024-07-01",
      category: "commercial-property",
      type: "sale",
      number_of_bedrooms: null,
      number_of_bathrooms: 4,
      location: "Ikeja, Lagos",
      state: "lagos",
      country: "Nigeria",
      image_count: 3,
      video: true,
      key_features: {
        mosque: true,
        church: true,
        security: true,
        hospital: true,
        gym: true,
        market: true,
        public_road: true,
        good_roads: true,
      },
    },
  ],
};
